version: '3'

services:
  frontend:
    build: ./frontend
    container_name: react-app
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - mern-networks
    volumes:
      - ./uploads:/app/uploads

  backend:
    build: ./backend
    container_name: node-api
    ports:
      - '5000:5000'
    restart: always
    depends_on:
      - database
    networks:
      - mern-networks
    volumes:
      - ./uploads:/app/uploads
      
  database:
    image: mongo
    container_name: mongo-db3
    restart: always
    ports:
      - '27017:27017'
    networks:
      - mern-networks

networks:
  mern-networks:
    driver: bridge
